### ISSUE TITLE
Feature Request: Hierarchically structured plucked data

### ISSUE THREAD

**Issue by grimnight** [schollz/pluck#9]
Assuming following config file:
```toml
# URL: https://www.pogdesign.co.uk/cat/
[[pluck]]
name = "day"
activators = ['href="./day/', 'title="']
deactivator = '"'

[[pluck]]
name = "show"
activators = ['<p data-episode', 'summary" >']
deactivator = '</a>'

[[pluck]]
name = "episode"
activators = ['<a href="', 'font-size: 0.65rem;">']
deactivator = '</a>'
```
It is possible to get the individual pieces of information from a webpage ("date", "show" and "episode"), but it is not hierarchically structured.

I would like to request a feature that allows to get the plucked data in a hierarchical structure.
